# The streaming control board's IP address
board_ip = "192.168.1.250"

# The instrument name
instrument_name = "TESTMACHINE"

# The firmware-generated xml file containing addresses of registers etc.
board_xml = "./example_xml/vxiscb_supermusr_ic_memory_map_output.xml"

# PV prefix of all PVs in this IOC
pv_prefix = "TE:TESTMACHINE:KDAECTRL:"

# Kafka topic on which to produce runInfo messages
# (usually <instrument>_runInfo)
runinfo_topic = "TESTMACHINE_runInfo"

# Kafka topic to use when putting sample environment placeholders in the run start message nexus_structure
sample_env_topic = "TESTMACHINE_sampleEnv"

# Kafka topic to use when putting event placeholders in the run start message's nexus_structure
events_topic = "TESTMACHINE_events"

# Local IP to send to the streaming board so it responds thereafter
local_ip = "192.168.1.17"

# file to save state to
state_file = "state.json"

[kafka_producer]
"bootstrap.servers" = "livedata.isis.cclrc.ac.uk:31092"
"enable.idempotence" = "true"
