valid_xml_str = """<?xml version="1.0" ?>
<node address="0x00000000" byte_size="536870912" hw_type="ic" id="vxiscb_supermusr_iconnect">
   <node absolute_id="vxiscb_supermusr_iconnect.run_period_control" absolute_offset="00000000" address="0x00000000" byte_size="128" id="run_period_control" link_done="run_period_control_memory_map_output.xml">
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.run_register" absolute_offset="00000000" address="0x00000000" description="Register to control the start of runs and run mode" hw_rst="0x0" id="run_register" permission="rw" size="1">
         <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.run_register.ethernet_override" absolute_offset="00000000" description="Bit0 = Ethernet override                                                                                                                                                       1=running,                                                                                                                                                       0=not running" hw_rst="0x0" id="ethernet_override" mask="0x00000001" permission="rw" size="1"/>
         <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.run_register.run_signal_select" absolute_offset="00000000" description="Bit2..1 = Run signal select                                                                                                                                                       3=VHDCI run allowing for short pause                                                                                                                                                       2=VXI synced run,                                                                                                                                                      1=Ethernet run signal                                                                                                                                                      0=VHDCI run signal" hw_rst="0x4" id="run_signal_select" mask="0x00000006" permission="rw" size="1"/>
         <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.run_register.increment_frame_counter" absolute_offset="00000000" description="Bit3 = Increment frame counter when run signal low                                                                                                                                                      0=increment counter, 1=don't increment counter" hw_rst="0x0" id="increment_frame_counter" mask="0x00000008" permission="rw" size="1"/>
      </node>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.frame_sync_sel" absolute_offset="00000004" address="0x00000004" description="Frame sync source select                                                                                                                                                      0=Internal,                                                                                                                                                       1=SMP,                                                                                                                                                       2=TOF" hw_rst="0x2" id="frame_sync_sel" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.internal_frame_period" absolute_offset="00000008" address="0x00000008" description="Internal frame sync period in µS (0x04E20=20ms,0x18600=100ms)" hw_rst="0x00004E20" id="internal_frame_period" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.frame_sync_delay" absolute_offset="0000000c" address="0x0000000c" description="Frame Sync time delay from frame source trigger (µS)" hw_rst="0x00000000" id="frame_sync_delay" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.fast_chopper_delay_0" absolute_offset="00000010" address="0x00000010" description="Fast chopper 0 window delay, 20 ns steps" hw_rst="0x00000000" id="fast_chopper_delay_0" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.fast_chopper_width_0" absolute_offset="00000014" address="0x00000014" description="Fast chopper 0 window length, 20 ns steps" hw_rst="0x00000000" id="fast_chopper_width_0" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.fast_chopper_delay_1" absolute_offset="00000018" address="0x00000018" description="Fast chopper 1 window delay, 20 ns steps" hw_rst="0x00000000" id="fast_chopper_delay_1" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.fast_chopper_width_1" absolute_offset="0000001c" address="0x0000001c" description="Fast chopper 1 window length, 20 ns steps" hw_rst="0x00000000" id="fast_chopper_width_1" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.fast_chopper_delay_2" absolute_offset="00000020" address="0x00000020" description="Fast chopper 2 window delay, 20 ns steps" hw_rst="0x00000000" id="fast_chopper_delay_2" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.fast_chopper_width_2" absolute_offset="00000024" address="0x00000024" description="Fast chopper 2 window length, 20 ns steps" hw_rst="0x00000000" id="fast_chopper_width_2" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.fast_chopper_delay_3" absolute_offset="00000028" address="0x00000028" description="Fast chopper 3 window delay, 20 ns steps" hw_rst="0x00000000" id="fast_chopper_delay_3" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.fast_chopper_width_3" absolute_offset="0000002c" address="0x0000002c" description="Fast chopper 3 window length, 20 ns steps" hw_rst="0x00000000" id="fast_chopper_width_3" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.period_control" absolute_offset="00000030" address="0x00000030" description="Period control register" hw_rst="0x0" id="period_control" permission="rw" size="1">
         <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.period_control.period_end_run_sequence" absolute_offset="00000030" description="Bit1 = End run at end of period sequence" hw_rst="0x0" id="period_end_run_sequence" mask="0x00000002" permission="rw" size="1"/>
         <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.period_control.period_mode" absolute_offset="00000030" description="bit5..4 = Period mode                                                                                                                                                      00: computer, 01: look up table                                                                                                                                                      10: not used), 11: external" hw_rst="0x3" id="period_mode" mask="0x00000030" permission="rw" size="1"/>
         <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.period_control.period_end_run_last_sequence" absolute_offset="00000030" description="Bit6 = End run after last period sequence" hw_rst="0x0" id="period_end_run_last_sequence" mask="0x00000040" permission="rw" size="1"/>
      </node>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.period_comp_current" absolute_offset="00000034" address="0x00000034" description="Current Period set by computer" hw_rst="0x00000000" id="period_comp_current" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.period_number_limit" absolute_offset="00000038" address="0x00000038" description="Period number limit" hw_rst="0xFFFFFFFF" id="period_number_limit" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.period_sequence_limit" absolute_offset="0000003c" address="0x0000003c" description="Period sequence limit" hw_rst="0xFFFFFFFF" id="period_sequence_limit" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.run_pause_wait_time" absolute_offset="00000040" address="0x00000040" description="Amount of time to wait when VXI_RUN goes to low before stopping the run (to account for pauses)" hw_rst="0x004C4B40" id="run_pause_wait_time" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.time_correction_enable" absolute_offset="00000044" address="0x00000044" description="Enable firmware that corrects the frame time due to inaccuracy of board oscillators" hw_rst="0x00000000" id="time_correction_enable" mask="0x00000001" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.time_correction_frame_length" absolute_offset="00000048" address="0x00000048" description="Register to set the frame length for the time correction process, time in ns. x3B9ACA00=1second (PPS), x01312D00=20ms (TS1), x05F5E100-100ms (TS2) " hw_rst="0x01312D00" id="time_correction_frame_length" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.enable_crc" absolute_offset="00000050" address="0x00000050" description="Register control if status packet uses CRC check" hw_rst="0x0" id="enable_crc" permission="rw" size="1">
         <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.enable_crc.rx" absolute_offset="00000050" description="Controls if the RX path should perform status packet check" hw_rst="0x1" id="rx" mask="0x00000001" permission="rw" size="1"/>
         <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.enable_crc.tx" absolute_offset="00000050" description="Controls if the TX path should perform status packet check" hw_rst="0x0" id="tx" mask="0x00000002" permission="rw" size="1"/>
      </node>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.crc_error_count" absolute_offset="00000054" address="0x00000054" description="A counter showing the amount of CRC errors detected" hw_rst="0x00000000" id="crc_error_count" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.crc_present" absolute_offset="00000058" address="0x00000058" description="A single bit flag that shows if a CRC is present" hw_rst="0x00000000" id="crc_present" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.crc_pass" absolute_offset="0000005c" address="0x0000005c" description="A single bit flag showing if the CRC is correct" hw_rst="0x00000000" id="crc_pass" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.years" absolute_offset="00000060" address="0x00000060" description="Current status packet time - years" hw_rst="0x00000000" id="years" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.days" absolute_offset="00000064" address="0x00000064" description="Current status packet time - days" hw_rst="0x00000000" id="days" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.hours" absolute_offset="00000068" address="0x00000068" description="Current status packet time - hours" hw_rst="0x00000000" id="hours" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.minutes" absolute_offset="0000006c" address="0x0000006c" description="Current status packet time - minutes" hw_rst="0x00000000" id="minutes" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.seconds" absolute_offset="00000070" address="0x00000070" description="Current status packet time - seconds" hw_rst="0x00000000" id="seconds" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.milliseconds" absolute_offset="00000074" address="0x00000074" description="Current status packet time - milliseconds" hw_rst="0x00000000" id="milliseconds" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.microseconds" absolute_offset="00000078" address="0x00000078" description="Current status packet time - microseconds" hw_rst="0x00000000" id="microseconds" mask="0xFFFFFFFF" permission="r" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.run_period_control.nanoseconds" absolute_offset="0000007c" address="0x0000007c" description="Current status packet time - nanoseconds" hw_rst="0x00000000" id="nanoseconds" mask="0xFFFFFFFF" permission="r" size="1"/>
   </node>
   <node absolute_id="vxiscb_supermusr_iconnect.udp_core" absolute_offset="10000000" address="0x10000000" byte_size="8192" hw_type="ic_merged" id="udp_core" link_done="udp_core_top_ic_memory_map_0_output.xml">
      <node absolute_id="vxiscb_supermusr_iconnect.udp_core.udp_core_control_0_dst_ip_addr" absolute_offset="10000024" address="0x00000024" description="UDP Destination(NIC) IP Address" hw_rst="0xC0A8017D" id="udp_core_control_0_dst_ip_addr" mask="0xFFFFFFFF" permission="rw" size="1"/>
      <node absolute_id="vxiscb_supermusr_iconnect.udp_core.udp_core_control_0_src_ip_addr" absolute_offset="10000028" address="0x00000028" description="UDP Source(Board) IP Address" hw_rst="0xC0A80103" id="udp_core_control_0_src_ip_addr" mask="0xFFFFFFFF" permission="rw" size="1"/>
   </node>
</node>
"""  # noqa: E501, RUF001
