"""IO utilities for saving and loading data which should persist."""

import json
import logging

from kafka_dae_control.data import Data

logger = logging.getLogger(__name__)


def save_file(data: "Data", *_: int) -> None:
    """Save relevant dataclass fields to a file.

    Args:
        data: the dataclass containing the state of the program
        *args: mandatory catch-all for hook signature.

    Returns: None

    """
    with open("test.json", "w", encoding="utf-8") as file:
        d = {"title": data.title.value, "users": data.users.value}
        logger.info("Saving %s to file", d)
        json.dump(d, file)


def load_file() -> dict[str, str | int]:
    """Load a file generated by a previous instance of this program.

    Returns: A populated dictionary with field values, or a default one if the file fails to load.

    """
    with open("test.json", encoding="utf-8") as file:
        try:
            return json.load(file)
        except json.decoder.JSONDecodeError as e:
            logger.error("Failed to load file (%s), defaulting all autosaved values", e)
            return {"title": "", "users": ""}
